### ISSUE TITLE
Import multiple sizes into one ico file?

### ISSUE THREAD

**Issue by Spunkie** [cdown/icopng#18]
All the tools I can find that combine multiple sizes in .ico, also convert pngs to bitmaps. So I'm not sure if it's possible... but it would be nice if `icopng` could do something like this:
```
icopng favicon-16x16.png favicon-32x32.png favicon-48x48.png favicon-192x192.png favicon.ico
```

**Comment by cdown** [comment]
It's a good idea. Only very sparingly tested, but #19 appears to do the right thing if you'd like to test it.
